### ISSUE TITLE
"a" and "o" vowels replaced by unicode ordinal indicators for Portuguese language in the output

### ISSUE THREAD

**Issue by scardine** [tesseract-ocr/tesseract#1084]
### Environment

* **Tesseract Version**: 4.0 
* **Commit Number**: 7afa05a03ed87a95a46da798fd11cae60f390441
* **Platform**: Ubuntu 17.04

### Current Behavior: 

For the following source images, the "a" and "o" vowels are replaced by "ª" and "º" (not the the superscript lower-case "a" and "o" but the feminine and masculine ordinal indicators, U+00AA and U+00BA) in the output:

![tag](https://user-images.githubusercontent.com/1397214/29376179-184fc66e-828e-11e7-8afb-21f058cd0348.png)

![tag2](https://user-images.githubusercontent.com/1397214/29376202-27dc8630-828e-11e7-9783-78da131212b5.png)

    $ tesseract notebooks/tag2.png stdout -l por
    Declªrªçãº de Nªscidº Vivº

### Expected Behavior: 

"a" and "o" verbatim:

    $ tesseract notebooks/tag2.png stdout -l por
    Declaração de Nascido Vivo

### What I have tried:

 * everything in the ImproveQuality wiki page
 * changing page segmentation modes and OCR engine
 * messing with character whitelists and blacklists
 * custom user word and pattern files
 * different fonts

Nothing made any difference.  

### Previous versions:

With 3.04 the output is like the expected.

**Comment by tomascharad** [comment]
Hi!

Same thing happens for spanish with letter 'o'

![screen shot 2017-08-16 at 6 06 34 pm](https://user-images.githubusercontent.com/1534092/29385359-c429e086-82ad-11e7-9efe-d99b17c2c887.png)

http://recursostic.educacion.es/observatorio/web/images/upload/1observatorio/iconos_art/texto.jpg

**Comment by scardine** [comment]
Confirmed, the same happens with the "o" in Spanish.

**Comment by amitdo** [comment]
https://en.wikipedia.org/wiki/Ordinal_indicator

**Comment by amitdo** [comment]
Can't reproduce this issue.

>tesseract por2.png por -l best/por

Or

>tesseract por2.png por -l best/por --oem 1

Output:

>Declaração de Nascido Vivo

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400

**Comment by scardine** [comment]
Nice. I was using [pre-built binaries](https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr) for Ubuntu from Alexander Pozdnyakov.

Problem is fixed in [that repository](https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr) now, new binaries were built from commit 7afa05a03ed87a95a46da798fd11cae60f390441

**Comment by scardine** [comment]
Please ignore the previous update, the package tesseract-ocr-por is not fixed yet.

I had to download from https://github.com/tesseract-ocr/tessdata/blob/master/best/por.traineddata and copy to /usr/share/tesseract-ocr/4.00/tessdata/por.traineddata

**Comment by amitdo** [comment]
You can also put in a sub directory (like 'best') under your tessdata dir and use -l subdir/lang

**Comment by paulaceccon** [comment]
I got the "new" files from [here](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400), but I still get the same result.

**Comment by scardine** [comment]
@paulaceccon where did you copy them to and how are you calling tesseract? (in order to help you diagnose the problem we must be able to reproduce it)
