### ISSUE TITLE
Build fails with -mno-fma set in global CXXFLAGS if build through configure

### ISSUE THREAD

**Issue by gordon-quad** [tesseract-ocr/tesseract#2841]
### Environment

* **Tesseract Version**: 4.1.1
* **Platform**: Linux asgard-hofud-chroot 5.3.6-gentoo-r1-x86_64 #1 SMP PREEMPT Tue Oct 15 11:34:29 BST 2019 x86_64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz GenuineIntel GNU/Linux

### Current Behavior:
```
$ export CFLAGS="-O2 -pipe -march=corei7-avx -mcx16 -msahf -mno-movbe -maes -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-tbm -mavx -msse4.2 -msse4.1 -mtune=corei7-avx -mindirect-branch=thunk"
$ export CXXFLAGS="$CFLAGS"
$ ./configure
[...]
$ make
[...]
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -O2 -DNDEBUG -I../../src/ccstruct -I../../src/ccutil -I../../src/viewer -I/usr/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/lib64/libffi/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/lib64/libffi/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -mfma -O2 -pipe -march=corei7-avx -mcx16 -msahf -mno-movbe -maes -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-tbm -mavx -msse4.2 -msse4.1 -mtune=corei7-avx -mindirect-branch=thunk -std=c++17 -MT libtesseract_fma_la-dotproductfma.lo -MD -MP -MF .deps/libtesseract_fma_la-dotproductfma.Tpo -c dotproductfma.cpp  -fPIC -DPIC -o .libs/libtesseract_fma_la-dotproductfma.o
dotproductfma.cpp:19:2: error: #error Implementation only for FMA capable architectures
 #error Implementation only for FMA capable architectures
  ^~~~~
```

### Expected Behavior:
Compile without an error.

### Suggested Fix:
Stop touching architecture and instruction set related cflags, leave it to host system to set.

**Comment by gordon-quad** [comment]
I guess it will also fail in similar manner with `-mno-avx`, `-mno-avx2` or `-mno-sse4.1` but I didn't test it.

**Comment by stweil** [comment]
Why should one want to set any of those compiler flags in `CXXFLAGS`?

**Comment by 1480c1** [comment]
I would understand with `-mfma`, but why would you set `-fno-*`? It would make since if you are attempting to compile with a small or moderatly unknown arch, but you're compiling for corei7-avx

**Comment by gordon-quad** [comment]
```
$ gcc -march=native -E -v - </dev/null 2>&1 | grep cc1
 /usr/libexec/gcc/x86_64-pc-linux-gnu/9.2.0/cc1 -E -quiet -v - -march=sandybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-sgx -mno-bmi2 -mno-pconfig -mno-wbnoinvd -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx5124fmaps -mno-avx5124vnniw -mno-clwb -mno-mwaitx -mno-clzero -mno-pku -mno-rdpid -mno-gfni -mno-shstk -mno-avx512vbmi2 -mno-avx512vnni -mno-vaes -mno-vpclmulqdq -mno-avx512bitalg -mno-movdiri -mno-movdir64b -mno-waitpkg -mno-cldemote -mno-ptwrite --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=sandybridge
```

That's the flags from march=native on the machine that I am compiling it *for*, but machine that I am compiling it *on* has fma. So I prefer to just take whatever cflags gcc is alreay using.

**Comment by stweil** [comment]
The compiler won't use FMA unless it is told so, so no need to set `-mno-fma`. The Tesseract build uses those SIMD flags only for selected files which are not used at runtime if the corresponding feature is unavailable.

**Comment by stweil** [comment]
Typically it is not necessary to set `CXXFLAGS`, and I would be surprised if there was a significant performance gain with your special mix of compiler flags.

**Comment by zdenop** [comment]
Is this issue valid also for the latest tesseract code?

**Comment by stweil** [comment]
I don't think it is a really an issue. A binary which is built on a machine with FMA (AVX2, ...) will also run on a machine without FMA (AVX2, ...) because Tesseract checks the available SIMD at runtime. The only exception is if someone uses the very special parameter `-c dotproduct=native`. Maybe we should disable that by default.

**Comment by zdenop** [comment]
Ff parameter is "dangerous" it should be turn off by default (e.g. it should be used only by users that knows what they are doing).

**Comment by stweil** [comment]
> I guess it will also fail in similar manner with `-mno-avx`, `-mno-avx2` or `-mno-sse4.1` but I didn't test it.

Yes, it will fail, and also with `-mno-avx512f` (see issue #3891) and future similar compiler flags.

**Comment by stweil** [comment]
Please explain why such values for `CXXFLAGS` might be required.

**Comment by luke-jr** [comment]
In my case, because I have multiple targets and want to optimise for one while keeping support for the others. Due to other CXXFLAGS, I need to be explicit about turning off features I can't assume are present on all targets.

Regardless, it should be fixed - either by having configure disable AVX/whatever support, or by overriding the user CXXFLAGS at build time too. ;)

**Comment by stweil** [comment]
Tesseract supports all your targets with optimized code by default. It has code fox AVX / AVX2 / AVX512 and so on which is only used on targets with that feature. Therefore I still don't understand why additional CXXFLAGS should be supported.

**Comment by luke-jr** [comment]
It is unreasonable to expect users to special-case CXXFLAGS for each piece of software they use, and there is no reason builds should fail rather than do the right thing.

**Comment by zdenop** [comment]
Tesseract build works on the standard/default setting of supported OS/distribution. If the user decides to modify default settings - the user is responsible for solving the problem.

**Comment by stweil** [comment]
I am afraid that the few main developers don't have free time for "fixing" things which don't need a fix because there is a very simple workaround (in this case: don't use compiler flags which are not needed) and therefore close this issue.

Anybody who wants a different solution is free to contribute a pull request.
